import { KonfikFactory } from '@konfik/core'
import type { Tsconfig } from 'tsconfig-type'

export const TsconfigKonfikBrand = Symbol.for('@konfik-plugin/tsconfig')
export type TsconfigKonfikBrand = typeof TsconfigKonfikBrand

export const TsconfigKonfik = KonfikFactory<Tsconfig>()({
  brand: TsconfigKonfikBrand,
  toString: (config) => {
    const prefix = `// NOTE: This file was generated by Konfik and should not be edited directly\n`
    return prefix + JSON.stringify(config, null, 2)
  },
  fileType: 'json',
})
